### ISSUE TITLE
Active Muting Rules not being taken into consideration

### ISSUE THREAD

**Issue by reliam-yoga** [newrelic-experimental/nr1-command-center#14]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )
We have recently started building some internal tooling that will fully leverage New Relic's Alert Muting NerdGraph capabilities. We were able to fully test and confirm the desired results were obtained, with the specific incidents having their State properly set as "Muted". However, we noticed that the "Muted" state is not something currently being considered on this Command Center application, with the incidents showing up as regular critical alerts, as opposed to indicating they are actually muted.  

## Desired Behaviour

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )
It would be highly appreciated to have either an indicator on the "Open Violations" list showcasing which incidents are actually silenced, or simply not showing them on the list at all. The first option being the preferable one.

**Comment by khpeet** [comment]
Thanks for the request @reliam-yoga! I will explore this further, but at first glance it may be tricky to combine the muted rules returned via graphql with the violation data being pulled via REST API. I'll see if there is a common response in both requests that we can use to key off of and mark a violation as muted or not.

**Comment by khpeet** [comment]
This will be fixed once violation data is available in NRDB to query or via GraphQL.

**Comment by khpeet** [comment]
fixed in v2 of this nerdpack: https://github.com/newrelic-experimental/nr1-command-center-v2  @reliam-yoga
