### ISSUE TITLE
Acknowledge/Close Not Working

### ISSUE THREAD

**Issue by tdavis13** [newrelic-experimental/nr1-command-center#17]
**SUMMARY**

When trying to acknowledge or close an incident from Command Center, it prompts for the API for the account.  However, after inputting the account and clicking on either Acknowledge or Close, no change occurs on the underlying alert.

**EXPECTED OUTCOME**

Acknowledge or Close should perform the stated action for the incident/alert in question.

**Comment by khpeet** [comment]
Are you inputting your admin REST API key for the account in which the violation resides? To find your admin key for a given account, check out this doc: https://docs.newrelic.com/docs/apis/get-started/intro-apis/types-new-relic-api-keys#admin

**Comment by tdavis13** [comment]
This does appear to be related to the wrong key.  This is a bit of a challenge to have those keys available for different accounts, etc.  But, it is not a bug as originally thought.
