### ISSUE TITLE
"Opened At" column does not match Incident

### ISSUE THREAD

**Issue by mission-fgimenez** [newrelic-experimental/nr1-command-center#19]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

When comparing the value provided on the "Opened At" column on the Command Center app with the "OPENED" date/time seen within the actual incident we see a disparity between the two. 

## Steps to Reproduce

Simply compare the "Opened At" column with the time seen within the incident under the "OPENED" section. 

## Expected Behaviour

"Opened At" column should match the time when the Violation was first opened, as seen within the Incident itself. 

## Additional context

Using Incident 151388698 as an example, on the Command Center we see the "Opened At" value as "08/13/2020 03:08", while the incident actually states "3:29 am OPENED"
![Screen Shot 2020-08-13 at 15 56 11](https://user-images.githubusercontent.com/69654614/90195240-cc82dc00-dd7d-11ea-8d05-c64e5f781e0e.png)
![Screen Shot 2020-08-13 at 15 57 10](https://user-images.githubusercontent.com/69654614/90195246-cd1b7280-dd7d-11ea-950f-547f024adbb6.png)

**Comment by khpeet** [comment]
@mission-fgimenez - Thanks for reporting this! Just merged a change that should fix this issue- please update the nerdpack to the new version!
