### ISSUE TITLE
Module failures when trying to start the nerdpack

### ISSUE THREAD

**Issue by sdeedee** [newrelic-experimental/nr1-command-center#2]
## Description

Module not found and module build failed errors when trying to start the nerdpack

## Steps to Reproduce

`nr1 nerdpack:serve`

## Relevant Logs / Console output

 `  ERROR in ./nerdlets/nr1-command-center-nerdlet/alarms.js
    Module not found: Error: Can't resolve 'moment' in '/root/GITLAB/nerdpack/nr1-command-center/nerdlets/nr1-command-center-nerdlet'
     @ ./nerdlets/nr1-command-center-nerdlet/alarms.js 17:0-28 489:20-26 758:22-28 759:22-28 806:17-23 806:29-35 995:25-31
     @ ./nerdlets/nr1-command-center-nerdlet/index.js

    ERROR in ./components/Configurator/index.js
    Module not found: Error: Can't resolve 'prop-types' in '/root/GITLAB/nerdpack/nr1-command-center/components/Configurator'
     @ ./components/Configurator/index.js 12:0-35 433:10-19 434:8-17 435:21-30
     @ ./nerdlets/nr1-command-center-nerdlet/alarms.js
     @ ./nerdlets/nr1-command-center-nerdlet/index.js

    ERROR in ./components/Configurator/Components/ToolPanel/index.js
    Module not found: Error: Can't resolve 'prop-types' in '/root/GITLAB/nerdpack/nr1-command-center/components/Configurator/Components/ToolPanel'
     @ ./components/Configurator/Components/ToolPanel/index.js 10:0-35
     @ ./components/Configurator/index.js
     @ ./nerdlets/nr1-command-center-nerdlet/alarms.js
     @ ./nerdlets/nr1-command-center-nerdlet/index.js

    ERROR in ./components/Configurator/Customisations/BaseInput.js
    Module not found: Error: Can't resolve 'prop-types' in '/root/GITLAB/nerdpack/nr1-command-center/components/Configurator/Customisations'
     @ ./components/Configurator/Customisations/BaseInput.js 5:0-35 98:8-17 99:17-26 100:11-20 101:14-23 102:14-23 103:14-23 104:15-24 105:14-23 106:12-21 107:13-22
     @ ./components/Configurator/index.js
     @ ./nerdlets/nr1-command-center-nerdlet/alarms.js
     @ ./nerdlets/nr1-command-center-nerdlet/index.js

    ERROR in ./nerdlets/nr1-command-center-nerdlet/alarms.js
    Module not found: Error: Can't resolve 'prop-types' in '/root/GITLAB/nerdpack/nr1-command-center/nerdlets/nr1-command-center-nerdlet'
     @ ./nerdlets/nr1-command-center-nerdlet/alarms.js 13:0-35 1474:20-29 1475:19-28 1476:9-18 1477:10-19
     @ ./nerdlets/nr1-command-center-nerdlet/index.js

    ERROR in ./components/Configurator/index.js
    Module not found: Error: Can't resolve 'react-jsonschema-form' in '/root/GITLAB/nerdpack/nr1-command-center/components/Configurator'
     @ ./components/Configurator/index.js 13:0-41 311:41-45
     @ ./nerdlets/nr1-command-center-nerdlet/alarms.js
     @ ./nerdlets/nr1-command-center-nerdlet/index.js

    ERROR in ./nerdlets/nr1-command-center-nerdlet/alarms.js
    Module not found: Error: Can't resolve 'react-table' in '/root/GITLAB/nerdpack/nr1-command-center/nerdlets/nr1-command-center-nerdlet'
     @ ./nerdlets/nr1-command-center-nerdlet/alarms.js 14:0-37 949:31-41
     @ ./nerdlets/nr1-command-center-nerdlet/index.js

    ERROR in ./tmp/d3d845e0-c97c-4acd-99e0-203d6ac6ebc4-styles.1583923439037.scss
    Module build failed (from /usr/lib/newrelic-cli/node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from /usr/lib/newrelic-cli/node_modules/fast-sass-loader/lib/index.js):
    Error: import file cannot be resolved: "@import '~react-table/react-table.css';" @/root/GITLAB/nerdpack/nr1-command-center/nerdlets/nr1-command-center-nerdlet/styles.scss
        at Object.importReplacer (/usr/lib/newrelic-cli/node_modules/fast-sass-loader/lib/index.js:207:19)
        at importReplacer.throw (<anonymous>)
        at onRejected (/usr/lib/newrelic-cli/node_modules/co/index.js:81:24)
        at process._tickCallback (internal/process/next_tick.js:68:7)
        at runLoaders (/usr/lib/newrelic-cli/node_modules/webpack/lib/NormalModule.js:316:20)
        at /usr/lib/newrelic-cli/node_modules/loader-runner/lib/LoaderRunner.js:367:11
        at /usr/lib/newrelic-cli/node_modules/loader-runner/lib/LoaderRunner.js:233:18
        at context.callback (/usr/lib/newrelic-cli/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
        at co.then.err (/usr/lib/newrelic-cli/node_modules/fast-sass-loader/lib/index.js:317:5)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    Child mini-css-extract-plugin ../../../../usr/lib/newrelic-cli/node_modules/css-loader/dist/cjs.js??ref--5-1!../../../../usr/lib/newrelic-cli/node_modules/postcss-loader/src/index.js??postcss!../../../../usr/lib/newrelic-cli/node_modules/fast-sass-loader/lib/index.js!tmp/d3d845e0-c97c-4acd-99e0-203d6ac6ebc4-styles.1583923439037.scss:
        Entrypoint mini-css-extract-plugin = *
        [../../../../usr/lib/newrelic-cli/node_modules/css-loader/dist/cjs.js?!../../../../usr/lib/newrelic-cli/node_modules/postcss-loader/src/index.js?!../../../../usr/lib/newrelic-cli/node_modules/fast-sass-loader/lib/index.js!./tmp/d3d845e0-c97c-4acd-99e0-203d6ac6ebc4-styles.1583923439037.scss] /usr/lib/newrelic-cli/node_modules/css-loader/dist/cjs.js??ref--5-1!/usr/lib/newrelic-cli/node_modules/postcss-loader/src??postcss!/usr/lib/newrelic-cli/node_modules/fast-sass-loader/lib!./tmp/d3d845e0-c97c-4acd-99e0-203d6ac6ebc4-styles.1583923439037.scss 574 bytes {mini-css-extract-plugin} [built] [failed] [1 error]

        ERROR in ./tmp/d3d845e0-c97c-4acd-99e0-203d6ac6ebc4-styles.1583923439037.scss (/usr/lib/newrelic-cli/node_modules/css-loader/dist/cjs.js??ref--5-1!/usr/lib/newrelic-cli/node_modules/postcss-loader/src??postcss!/usr/lib/newrelic-cli/node_modules/fast-sass-loader/lib!./tmp/d3d845e0-c97c-4acd-99e0-203d6ac6ebc4-styles.1583923439037.scss)
        Module build failed (from /usr/lib/newrelic-cli/node_modules/fast-sass-loader/lib/index.js):
        Error: import file cannot be resolved: "@import '~react-table/react-table.css';" @/root/GITLAB/nerdpack/nr1-command-center/nerdlets/nr1-command-center-nerdlet/styles.scss
            at Object.importReplacer (/usr/lib/newrelic-cli/node_modules/fast-sass-loader/lib/index.js:207:19)
            at importReplacer.throw (<anonymous>)
            at onRejected (/usr/lib/newrelic-cli/node_modules/co/index.js:81:24)
            at process._tickCallback (internal/process/next_tick.js:68:7)
    Error: The build failed.
     You can run this command with "--verbose" for more info.`

**Comment by khpeet** [comment]
Similar to #3, I believe an update to the CLI will fix this

**Comment by sdeedee** [comment]
Seems to work. Thanks!
