### ISSUE TITLE
Include custom violation description from NRQL alert

### ISSUE THREAD

**Issue by mtsou-nr** [newrelic-experimental/nr1-command-center#22]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
When using FACET with NRQL alert conditions, user can add FACETed attributes as custom violation description. This descriptions will allow user to see what combination of attributes is having a violation.

## Desired Behaviour
Adding custom violation descriptions as additional columns in the table presentation or combine them as one space separated text field. 

## Possible Solution
The custom violation descriptions are available in the NrAiIncident events. 

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by khpeet** [comment]
fixed in v2 of this nerdpack: https://github.com/newrelic-experimental/nr1-command-center-v2 @mtsou-nr
