### ISSUE TITLE
nerdpack uuid error

### ISSUE THREAD

**Issue by sdeedee** [newrelic-experimental/nr1-command-center#3]
## Description

Default uuid generated in nr1.json file is not allowed (starts with an integer but not allowed).

## Steps to Reproduce

starting the application the first time

## Relevant Logs / Console output

`undefined:
    2ced9f6f-ef74-46a6-bd10-6fa2146e71f1 nr1.json
    └ Property /id The id must be lowercase, start with a letter and can only contain alphabetic characters, numbers and hyphens. E.g: my-nerdlet-id. Should match the regular expression: ^[a-z0-9-]+$.`

**Comment by khpeet** [comment]
@sdeedee - what version node/npm/nr1 are you running?

```
npm -v
node -v
nr1 -v
```

**Comment by sdeedee** [comment]
nr1-command-center# npm -v
3.5.2
nr1-command-center# node -v
v8.10.0
nr1-command-center# nr1 -v
@datanerd/nr1/1.2.2 linux-x64 node-v10.16.3

**Comment by khpeet** [comment]
Looks like an older version of the CLI - can you run `nr1 update` to get on the latest version (I believe 1.19.5?)

**Comment by sdeedee** [comment]
Seems to work. Thanks!

**Comment by rodrigo-corgozinho** [comment]
Hi guys.. I'm having the same issue.

I've just downloaded the nerdpack

These are the versions:
```
npm -v && node -v && nr1 -v
6.14.11
v14.0.0
@datanerd/nr1/1.32.0 darwin-x64 node-v10.16.3
```

Running `nr1 update` didn't help.

thanks
