### ISSUE TITLE
Overview not loading with large number of subaccounts

### ISSUE THREAD

**Issue by sdeedee** [newrelic-experimental/nr1-command-center#4]
Overview keeps loading when adding +10 (sub)accounts
## Description

When adding a config with + 10 (sub)accounts the config is successful saved but refreshing account data keeps loading. 

## Additional context

We want to use this in a MSP context to have a quick overview on all accounts. Didn't test yet if the number of accounts is the problem or if it's the number of open violations that results in a "keep loading".

**Comment by khpeet** [comment]
@sdeedee - I've tested with 1000+ violations and up to 30-40 sub accounts. The app typically loads within 30-40 seconds from that kind of load.

**Comment by sdeedee** [comment]
@khpeet - I did some more tests and at the end the config is loaded correctly. I have now a setup of 90 subaccounts. Initially run takes +- 10m/15m. After first loading of the dashboard I can see a normal refreshing rate.

**Comment by khpeet** [comment]
@sdeedee - how many violations are loaded total across those 90 accounts?

**Comment by sdeedee** [comment]
all together > 20000 warning violations (1 particular account has > 16000, but I'll check which is causing this)

**Comment by khpeet** [comment]
Thanks! Definitely don't want that many violations opened in any given account- I think the policies/conditions need to be refined.

Eventually, once violations are available to retrieve via our [graphql api](https://docs.newrelic.com/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph) (versus the REST API) - this should improve performance/efficiency in which violations are retrieved.

**Comment by tdavis13** [comment]
I don't want to assume the same issue, but don't want to open a new issue without asking.  I am unable to save a fifth account and have it persist across connections.  I can save it and it will be viewable 'now'.  However, if I go away and come back, I am back to the previous 4 I loaded.  Same/Similar issue or report separately?

**Comment by khpeet** [comment]
@tdavis13 - that sounds like a separate issue - can you open a new issue for that?

**Comment by khpeet** [comment]
fixed in v2 of this nerdpack: https://github.com/newrelic-experimental/nr1-command-center-v2 @tdavis13
