### ISSUE TITLE
configuration not persistent

### ISSUE THREAD

**Issue by sdeedee** [newrelic-experimental/nr1-command-center#5]
It seems like added account configuration isn't persistent. 
## Description

When reloading the nr1-command-center from one.newrelic.com startpage, configuration is cleared and configured accounts are gone.

**Comment by khpeet** [comment]
@sdeedee - Are you an admin/user within the accountId that you specified within `alarms.js` ? Also, when starting the application with `nr1 nerdpack:serve`, the profile (account) that you are serving to typically has to match the account specified in `alarms.js` You can check what your default profile is with the command `nr1 profiles:list`

**Comment by khpeet** [comment]
@sdeedee - closing this since it is not a bug, but a configuration issue
