### ISSUE TITLE
adding filter options to the open violations tab

### ISSUE THREAD

**Issue by sdeedee** [newrelic-experimental/nr1-command-center#6]
## Summary

It would be nice to have filter options in the open violations tab. Especially when you have a lot of accounts/open violations. 

## Desired Behaviour

- option to filter on a (sub)account

- option to filter on a specific condition/policy name

- filter on incident and grouping warnings/criticals that belong to one incident

**Comment by khpeet** [comment]
This is doable - I'll add this in the next release
