### ISSUE TITLE
possibility to configure a webhook in the violation overview

### ISSUE THREAD

**Issue by sdeedee** [newrelic-experimental/nr1-command-center#8]
## Summary

It would be nice to have webhook functionality in the open violations tab. 

## Desired Behaviour

Webhook functionality combined with custom buttons makes work easy to quickly react on alerts and dispatch them:

- ack button linked to NR ack functionality so other team members can see someone is already taken action on an alert

- custom button for example "create ticket". This button calls a webhook to a external ticket system and creates a ticket linked to the alert. 

- additional bidirectional webhook functionality makes it possible to add the link of the created ticket as a link in the open violations tab

**Comment by khpeet** [comment]
- ack button linked to NR ack functionality so other team members can see someone is already taken action on an alert
**This is similar to #7**

- custom button for example "create ticket". This button calls a webhook to a external ticket system and creates a ticket linked to the alert.
**This already exists within New Relic Alerts directly - webhook notification channels attached to a given policy will automatically create an event/incident within an external system. Having a button in the open violations view that does that manually duplicates the webhook functionality in the platform.**


- additional bidirectional webhook functionality makes it possible to add the link of the created ticket as a link in the open violations tab
**This type of functionality exists already within the Links column (without adding the ticket link automatically) - you can manually link a ticket in a 3rd party system that will persist to any user accessing the view. We also have bi-directional communication in the works with ServiceNow within our core Alerts product (coming soon).**

**Comment by sdeedee** [comment]
Today there's still no MSP overview/all (sub)accounts alerting violations in the native NR platform. So alerting/notification channels/ack is configured within each (sub)account. The command-center dashboard shows all violations in all (sub)accounts so if also the ack/create ticket could be done from within this view ... would be nice. 

Interesting to know bi-directional communication with ServiceNow is comming soon.
