### ISSUE TITLE
incident information in the summary overview

### ISSUE THREAD

**Issue by sdeedee** [newrelic-experimental/nr1-command-center#9]
## Summary

It would be nice to see not only the number of critical/warning violations but also the amount of open incidents. 
## Desired Behaviour

Incidents vs violations have a 1-many relationship. With displaying the number of open incidents, people have a good insight if there's something total wrong (number of critical violations = number of incidents) or if there's something not correctly configured/something is flapping (number of criticals/warnings x time > number of incidents.

**Comment by khpeet** [comment]
Would this be more useful on the summary page or within the open violations tab?

**Comment by sdeedee** [comment]
On the summary page would be nice.
